I hate twitter API limit, so i put it in the /about page. I show github commit instead in my home to immediately show visitors I use commits to explain WHY, not HOW (there is the diff for the that)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -79,6 +79,10 @@ jobs:
             echo "Error: TWITTER_BEARER_TOKEN secret is not set"
             exit 1
           fi
+          if [ -z "${{ secrets.PERSONAL_GITHUB_TOKEN }}" ]; then
+            echo "Error: PERSONAL_GITHUB_TOKEN secret is not set"
+            exit 1
+          fi
 
       - name: Deploy to Hetzner
         uses: appleboy/ssh-action@master
@@ -105,6 +109,7 @@ jobs:
             echo "GOOGLE_APP_USER=${{ secrets.GOOGLE_APP_USER }}" >> .env
             echo "GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}" >> .env
             echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env
+            echo "PERSONAL_GITHUB_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }}" >> .env
 
             # Login to GitHub Container Registry
             echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
